
 CREATE TABLE AP_GALVANICA_MODELLO 
   (	
      IDMAGAZZ VARCHAR2(10 BYTE) NOT NULL, 
      IDMAGAZZ_WIP VARCHAR2(10 BYTE) NOT NULL,
      MODELLO	VARCHAR2(30 BYTE) NOT NULL,
      COMPONENTE	VARCHAR2(30 BYTE) NOT NULL,
      BRAND	VARCHAR2(20 BYTE)NOT NULL,
      FINITURA	VARCHAR2(20 BYTE) NOT NULL,  
      MATERIALE VARCHAR2(20 BYTE) NOT NULL, 
      PEZZIBARRA NUMBER NULL,
      SUPERFICIE VARCHAR(10) NULL,
      GALVANICA VARCHAR2(20) NOT NULL
   );
   
   CREATE INDEX IDX_AP_GALVANICA_MODELLO ON AP_GALVANICA_MODELLO(IDMAGAZZ,IDMAGAZZ_WIP);
   
   
 CREATE TABLE AP_GALVANICA_PIANO
   (	
   IDGALVAPIANO NUMBER NOT NULL,
      IDMAGAZZ VARCHAR2(10 BYTE) NOT NULL, 
      IDMAGAZZ_WIP VARCHAR2(10 BYTE) NOT NULL,
      MODELLO	VARCHAR2(30 BYTE) NOT NULL,
      COMPONENTE	VARCHAR2(30 BYTE) NOT NULL,
      BRAND	VARCHAR2(20 BYTE)NOT NULL,
      FINITURA	VARCHAR2(20 BYTE) NOT NULL,  
      MATERIALE VARCHAR2(20 BYTE) NOT NULL, 
      PEZZIBARRA NUMBER NULL,
      SUPERFICIE VARCHAR(10) NULL,
      ORDINE NUMBER NULL,
      GALVANICA VARCHAR2(20) NOT NULL,
      QUANTITA NUMBER NULL,
      PIANIFICATO NUMBER NULL,
      BARRE FLOAT NULL,
      DATAGALVANICA DATE,
       PRIMARY KEY (IDGALVAPIANO)
   );
   
      CREATE INDEX IDX_AP_AP_GALVANICA_PIANO ON AP_GALVANICA_PIANO(DATAGALVANICA);
