
 CREATE TABLE AP_PREVENTIVIT 
   (	
   IDPREVENTIVOT NUMBER NOT NULL, 
   IDVENDITEPF	VARCHAR2(25 BYTE) NOT NULL,
  CODPROVVISORIO VARCHAR2(15) NULL,
  CODDEFINITIVO VARCHAR2(15) NULL,
  CODGALVANICA VARCHAR2(15) NULL,
  FORNITORE VARCHAR2(15) NULL,
  DESCRIZIONE VARCHAR2(50) NULL,
  STAGIONE VARCHAR2(10) NULL,
  EVENTO VARCHAR2(10) NULL,
  "DATA" DATE NOT NULL,
    SPESSOREAU VARCHAR2(10) NULL,
    SPESSOREPD VARCHAR2(10) NULL,
    SUPERFICIE VARCHAR2(8) NULL,
    PESO VARCHAR2(8) NULL,
    COMPOSIZIONE VARCHAR2(100) NULL,
    RICARICO FLOAT NULL,
	 PRIMARY KEY (IDPREVENTIVOT)
   );
   
  CREATE INDEX IDX_AP_PREVENTIVIT_1 ON AP_PREVENTIVIT(IDVENDITEPF);

 CREATE TABLE AP_PREVENTIVIG 
   (	"IDVENDITEPFGRUPPOT" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
IDPREVENTIVOT NUMBER NOT NULL,
"IDVENDITEPF" VARCHAR2(25 BYTE), 
	"IDVENDITEPD" VARCHAR2(25 BYTE), 
	"IDVENDITEPT" VARCHAR2(25 BYTE), 
	"IDVENDITEPFDIBA" VARCHAR2(25 BYTE), 
	"IDPREVGRUPPO" VARCHAR2(10 BYTE), 
	"SEQUENZA" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALECOSTI" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALERICARICO" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALEVENDITA" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALEVENDITACALCOLATO" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALEVENDITAMANUALEG" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"TOTALEVENDITAMANUALET" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
  "DATA" DATE NOT NULL,
  CODVOCECOSTO	VARCHAR2(100 BYTE),
  DESVOCECOSTO	VARCHAR2(254 BYTE),
	 PRIMARY KEY ("IDVENDITEPFGRUPPOT")
   ) ;
   
CREATE INDEX IDX_AP_PREVENTIVIG_1 ON AP_PREVENTIVIG(IDVENDITEPF);

 
  CREATE TABLE AP_PREVENTIVIC 
   (	"IDVENDITEPFDIBACOS" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"IDVENDITEPFDIBA" VARCHAR2(25 BYTE), 
	"SEQUENZA" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"VALOREFISSO" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"QTAFISSA" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"VALORENETTO" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
   "DATA" DATE NOT NULL,
  "IDVENDITEPF" VARCHAR2(25 BYTE), 
	 PRIMARY KEY ("IDVENDITEPFDIBACOS")
   ) ;

CREATE INDEX IDX_AP_PREVENTIVIC_1 ON AP_PREVENTIVIC(IDVENDITEPF);

